import type { SceneContext } from '../../../types/dialogue';

const context = (time: string, goal: string, knownFacts: string[] = [], immediateRisk: SceneContext['immediateRisk'] = 'medium'): SceneContext => ({
  time,
  playerLocation: 'shared_apartment',
  characterLocation: 'katya_apartment',
  sceneGoal: goal,
  knownFacts,
  immediateRisk,
});

export const lubovSceneContexts: Record<string, SceneContext> = {
  lubov_start: context('22:46', 'send first evidence', ['denis_sent_distant_photos']),
  lubov_reaction_explain: context('22:47', 'process the demand for explanation', ['lyubov_recognizes_photo']),
  lubov_reaction_deny: context('22:47', 'react to shock and denial', ['lyubov_recognizes_photo']),
  lubov_reaction_ultimatum: context('22:47', 'react to the demand for truth', ['lyubov_recognizes_photo']),
  lubov_reaction_sarcastic: context('22:47', 'deflect sarcasm and identify source', ['lyubov_recognizes_photo']),
  lubov_reaction_rage: context('22:47', 'contain initial rage', ['lyubov_recognizes_photo']),
  lubov_first_version: context('22:50', 'offer the one-kiss story', ['artyom_is_colleague', 'lyubov_claims_one_kiss']),
  lubov_ask_man: context('22:53', 'identify Artyom', ['artyom_is_colleague']),
  lubov_ask_place: context('22:53', 'identify the hotel area', ['hotel_sever']),
  lubov_ask_katya: context('22:53', 'test the Katya alibi', ['katya_alibi']),
  lubov_call_lie: context('22:53', 'defend the first version', ['lyubov_claims_one_kiss']),
  lubov_first_questions: context('22:57', 'lock dates and claims before more evidence', ['lyubov_claims_one_kiss', 'artyom_knows_marriage']),
  lubov_evidence_break: context('23:10', 'break the first version with timestamps', ['old_message_0103', 'hotel_photo_0117'], 'high'),
  lubov_partial_admission: context('23:14', 'admit repeated meetings without full emotional truth', ['four_meetings', 'two_months_physical']),
  lubov_chat_offer: context('23:17', 'decide how much chat evidence to reveal', ['planned_lie_possible']),
  lubov_planned_chat: context('23:21', 'show planned Katya lie', ['meeting_planned', 'alibi_planned']),
  lubov_timeline_partial: context('23:21', 'give dates without full chat', ['four_meetings']),
  lubov_no_chat: context('23:21', 'continue with reduced evidence', ['chat_withheld']),
  lubov_forward_stay: context('23:25', 'reveal Artyom wanted more', ['artyom_asked_stay']),
  lubov_forward_answer: context('23:28', 'reveal Lyubov protected the double life', ['lyubov_answered_until_morning']),
  lubov_boundary_one: context('23:29', 'set a boundary against humiliation', ['conflict_escalated']),
  lubov_full_admission: context('23:32', 'state the fixed timeline and responsibility', ['four_meetings', 'planned_lies', 'katya_refused_cover']),
  lubov_timeline_crosscheck: context('23:35', 'audit contradictions explicitly', ['one_kiss_disproved', 'timeline_fixed']),
  lubov_full_chat: context('23:37', 'show the last withheld emotional evidence', ['artyom_asked_choose']),
  lubov_rage_peak: context('23:40', 'release anger without physical threats', ['planned_lies_proven'], 'high'),
  lubov_boundary_two: context('23:42', 'stop repeated abuse or end contact', ['second_boundary']),
  lubov_after_rage: context('23:44', 'move from rage to the reason', ['affair_admitted']),
  lubov_why: context('23:47', 'explain marriage problems without excusing betrayal', ['marriage_cold_eleven_months']),
  lubov_love_question: context('23:49', 'answer whether she loves Artyom', ['emotional_attachment']),
  lubov_loved_me: context('23:51', 'answer whether love for husband was real', ['contradictory_attachment']),
  lubov_artem_choice: context('23:52', 'decide whether contact with Artyom ends', ['artem_contact_active']),
  lubov_caught_question: context('23:54', 'answer what would happen without discovery', ['no_plan_to_confess']),
  lubov_tonight: context('23:56', 'decide where Lyubov sleeps', ['lyubov_at_katya']),
  lubov_suitcase: context('23:57', 'make separation concrete', ['suitcase_for_days']),
  lubov_keys_context: context('23:58', 'clarify which keys remain', ['spare_keys_on_table']),
  lubov_property_boundary: context('23:58', 'prevent destruction of shared property', ['property_joint']),
  lubov_property_transition: context('23:59', 'move from tonight to joint obligations', ['apartment_joint', 'mortgage_open']),
  lubov_mortgage: context('00:01', 'establish shared debt', ['mortgage_3870000']),
  lubov_bank: context('00:03', 'establish that savings are intact', ['savings_1240000']),
  lubov_final_decision: context('00:05', 'choose the future of marriage', ['truth_available', 'property_known'], 'resolved'),
  lubov_divorce_tone: context('00:06', 'choose how the divorce proceeds', ['divorce_chosen'], 'resolved'),
  lubov_end_period_node: context('00:06', 'end the marriage', ['marriage_over'], 'resolved'),
  lubov_end_war_node: context('00:06', 'end in legal conflict', ['legal_war'], 'resolved'),
  lubov_end_blocked_node: context('23:43', 'end abusive communication', ['contact_blocked'], 'resolved'),
  lubov_end_separate_node: context('00:06', 'begin temporary separation', ['temporary_separation'], 'resolved'),
  lubov_end_honest_divorce_node: context('00:06', 'separate with respect', ['honest_divorce'], 'resolved'),
  lubov_end_try_again_node: context('00:06', 'attempt repair after no-contact', ['repair_attempt'], 'resolved'),
  lubov_end_without_trust_node: context('00:06', 'remain for practical fear', ['staying_without_trust'], 'resolved'),
  lubov_end_whole_truth_node: context('00:06', 'close the evidence audit', ['whole_truth'], 'resolved'),
  lubov_end_chooses_him_node: context('00:06', 'end after refusing no-contact', ['chooses_artem'], 'resolved'),
};
