import type { SceneContext } from '../../../types/dialogue';

const context = (
  time: string,
  playerLocation: string,
  characterLocation: string,
  sceneGoal: string,
  knownFacts: string[],
  immediateRisk: SceneContext['immediateRisk'],
  markLocation?: string,
): SceneContext => ({ time, playerLocation, characterLocation, sceneGoal, knownFacts, immediateRisk, markLocation });

export const camilaSceneContexts: Record<string, SceneContext> = {
  start: context('21:18', 'apartment_46_or_47_if_risky_start', 'restoration_workshop', 'player_initiates_contact', [], 'low', 'unknown'),
  warm_1: context('21:19', 'apartment_46', 'restoration_workshop', 'identify_blue_envelope', ['blue_envelope'], 'low', 'unknown'),
  warm_2: context('21:25', 'apartment_46', 'restoration_workshop', 'establish_envelope_was_delivered_recently', ['blue_envelope', 'camila_did_not_address_envelope'], 'medium', 'unknown'),
  bold_1: context('21:19', 'apartment_46', 'restoration_workshop', 'identify_key_without_exposing_address', ['brass_key'], 'low', 'unknown'),
  bold_2: context('21:25', 'apartment_46', 'restoration_workshop', 'connect_key_to_apartment_47', ['key_opens_47', '47_declared_empty'], 'medium', 'unknown'),
  flirt_1: context('21:19', 'apartment_46', 'restoration_workshop', 'move_from_joke_to_real_risk', ['brass_key'], 'low', 'unknown'),
  flirt_2: context('21:25', 'apartment_46', 'restoration_workshop', 'introduce_alina_without_infodump', ['key_opens_47', 'alina_is_camilas_sister'], 'medium', 'unknown'),
  careful_1: context('21:19', 'apartment_46', 'restoration_workshop', 'confirm_player_is_safe', ['object_at_player_door'], 'low', 'unknown'),
  careful_2: context('21:25', 'apartment_46', 'restoration_workshop', 'establish_key_came_from_marks_office', ['key_seen_with_manager', 'key_moved_today'], 'medium', 'unknown'),
  risky_1: context('21:19', 'apartment_47', 'restoration_workshop', 'get_player_back_home', ['key_opens_47', 'player_name_on_wall'], 'high', 'unknown'),
  risky_2: context('21:27', 'apartment_46', 'restoration_workshop', 'record_precise_details_from_47', ['player_entered_47', 'player_name_on_wall'], 'medium', 'unknown'),
  crossing: context('21:42', 'apartment_46', 'transit_to_building', 'introduce_alina_and_set_remote_plan', ['alina_is_camilas_sister', 'alina_disappeared', 'key_opens_47'], 'medium', 'unknown'),
  stairwell: context('22:18', 'apartment_46', 'stairwell_floor_6', 'observe_and_introduce_mark', ['mark_is_manager', 'mark_had_key', '47_linked_to_alina'], 'high', 'landing_outside_47'),
  threshold: context('22:24', 'apartment_46', 'apartment_39', 'open_second_envelope_and_motivate_return_to_47', ['second_envelope', 'player_file_in_47', 'door_47_open'], 'high', 'leaving_building_or_unknown'),
  archive: context('22:36', 'apartment_46', 'apartment_47', 'preserve_minimal_evidence', ['archive_has_twelve_people', 'player_was_observed', 'mark_access_log'], 'high', 'unknown'),
  recording: context('22:45', 'apartment_46', 'apartment_47', 'discover_alina_recording_and_camilas_prior_knowledge', ['player_is_thirteenth', 'camila_knew_file_existed'], 'high', 'unknown'),
  interlude: context('22:55', 'apartment_46', 'apartment_39', 'confess_key_plant_and_restore_safety', ['camila_selected_player', 'camila_planted_key', 'camila_did_not_send_envelope'], 'medium', 'unknown'),
  midnight: context('23:17', 'apartment_46', 'apartment_39', 'respond_to_unknown_person_without_opening', ['person_outside_camila', 'alina_childhood_phrase'], 'high', 'unknown'),
  second_room: context('23:23', 'apartment_46', 'apartment_39', 'audit_surviving_evidence', ['old_photo_delivered', 'author_knows_about_copy'], 'high', 'unknown'),
  fracture: context('23:31', 'apartment_46', 'apartment_39', 'prove_recording_is_spliced', ['recording_is_new_montage', 'mark_had_archive_access'], 'high', 'service_area_or_unknown'),
  mark: context('23:48', 'apartment_46', 'apartment_39', 'handle_direct_threat_from_marks_number', ['threat_demands_key_and_file', 'person_at_camila_door'], 'high', 'unknown'),
  aftershock: context('00:02', 'apartment_46', 'apartment_39', 'show_consequences_and_camilas_signature', ['person_left', 'camera_image_is_ambiguous', 'camila_signed_old_forms'], 'medium', 'moving_toward_service_area'),
  reckoning: context('01:26', 'apartment_46', 'apartment_39', 'assemble_proven_facts_after_police_action', ['mark_detained', 'server_recovered', 'alina_status_unknown'], 'resolved', 'police_custody'),
  decision: context('01:32', 'apartment_46', 'apartment_39', 'choose_evidence_and_relationship_outcome', ['main_threat_resolved', 'camila_accountable', 'evidence_status_known'], 'resolved', 'police_custody'),
  end_good_dawn: context('06:18', 'building_entrance', 'building_entrance', 'first_in_person_meeting_after_truth', ['evidence_preserved', 'trust_restored'], 'resolved', 'police_custody'),
  end_good_equal: context('06:18', 'building_entrance', 'building_entrance', 'first_meeting_with_explicit_boundaries', ['tests_rejected', 'mutual_interest'], 'resolved', 'police_custody'),
  end_neutral_archive: context('morning', 'apartment_46', 'apartment_39', 'close_personal_contact_but_preserve_case', ['evidence_preserved', 'relationship_ended'], 'resolved', 'police_custody'),
  end_neutral_truth: context('morning', 'apartment_46', 'apartment_39', 'leave_future_contact_undefined', ['facts_accepted', 'trust_not_restored'], 'resolved', 'police_custody'),
  end_bad_erased: context('next_day', 'apartment_46', 'unknown', 'show_cost_of_destroying_evidence', ['archive_destroyed', 'mark_released'], 'high', 'released'),
  end_bad_blocked: context('morning', 'apartment_46', 'apartment_39', 'complete_emotional_break_and_block', ['boundaries_ignored', 'relationship_broken'], 'resolved', 'police_custody'),
  end_secret: context('07:14', 'slyudyanka_station', 'slyudyanka_station', 'first_meeting_and_find_alina', ['alina_alive', 'envelope_from_alina'], 'resolved', 'police_custody'),
};
