import type { LubovCopy } from '../graph';

export const lubovEnCopy: LubovCopy = {
  lubov_start_proof: 'That is you. And this does not look like a work meeting.',
  lubov_start_source: 'Photo received from Denis at 10:40 PM today. Taken from a distance on a phone camera.',
  lubov_start_explain: 'Explain.',
  lubov_start_deny: 'Tell me that is not you.',
  lubov_start_ultimatum: 'You have one chance to tell me the truth.',
  lubov_start_sarcastic: 'Interesting way to spend your “night at Katya’s.”',
  lubov_start_rage: 'WHO IS HE, LYUBOV?',

  lubov_reaction_explain_1: 'where did you get this?',
  lubov_reaction_explain_2: 'who took it?',
  lubov_reaction_explain_3: 'are you home right now?',
  lubov_reaction_explain_notice: 'You did not even ask what was in the photo.',
  lubov_reaction_explain_source: 'Denis saw you outside the Sever. Now explain.',
  lubov_reaction_explain_repeat: 'Do not change the subject. Who is he?',

  lubov_reaction_deny_1: 'oh god',
  lubov_reaction_deny_2: 'where did you get that photo?',
  lubov_reaction_deny_3: 'please do not decide what happened before I explain',
  lubov_reaction_deny_notice: 'You recognized it before you asked what it showed.',
  lubov_reaction_deny_confirm: 'I can see your face. Do not make me doubt my own eyes.',
  lubov_reaction_deny_source: 'Denis sent it. He took it from across the parking lot.',

  lubov_reaction_ultimatum_1: 'I understand',
  lubov_reaction_ultimatum_2: 'just tell me where the photo came from first',
  lubov_reaction_ultimatum_3: 'I need to know who else has seen it',
  lubov_reaction_ultimatum_notice: 'You care about who saw it, not what you did.',
  lubov_reaction_ultimatum_truth: 'No. Truth first. Source afterward.',
  lubov_reaction_ultimatum_source: 'Denis. I do not know who else.',

  lubov_reaction_sarcastic_1: 'do not do that',
  lubov_reaction_sarcastic_2: 'yes, I know how it looks',
  lubov_reaction_sarcastic_3: 'who sent it?',
  lubov_reaction_sarcastic_notice: 'It looks like what happened. You were not even surprised.',
  lubov_reaction_sarcastic_drop: 'Fine. No sarcasm. I want the truth.',
  lubov_reaction_sarcastic_press: 'Do you want to know who else will need your version?',

  lubov_reaction_rage_1: 'do not shout at me through messages',
  lubov_reaction_rage_2: 'I will answer',
  lubov_reaction_rage_3: 'but tell me where this came from first',
  lubov_reaction_rage_notice: 'You already know what the photo shows. That is why you are only asking about the source.',
  lubov_reaction_rage_repeat: 'WHO IS HE?',
  lubov_reaction_rage_control: 'I am furious. Give me facts: who is he and how long has this been going on?',

  lubov_first_version_1: 'yes',
  lubov_first_version_2: 'that is me',
  lubov_first_version_3: 'his name is Artyom. he works with me',
  lubov_first_version_4: 'it was one kiss. one time. I regretted it immediately',
  lubov_first_version_5: 'and yes. you are right. I did not ask what the photo showed because I knew immediately',
  lubov_ask_who: 'Who is Artyom?',
  lubov_ask_where: 'Where exactly was this?',
  lubov_ask_katya_choice: 'That night you told me you were at Katya’s.',
  lubov_ask_call_lie: '“One time” already sounds rehearsed.',

  lubov_ask_man_1: 'he runs the project team next to mine',
  lubov_ask_man_2: 'we met at work four months ago',
  lubov_ask_man_3: 'at first we genuinely only talked about projects',
  lubov_ask_man_4: 'he knows I am married',
  lubov_ask_man_continue: 'When did it stop being about work?',
  lubov_ask_man_married: 'He knew about me and still went along with this?',
  lubov_ask_man_feelings: 'And what did you feel for him then?',

  lubov_ask_place_1: 'outside the restaurant beside the Sever',
  lubov_ask_place_2: 'we had just come out after dinner',
  lubov_ask_place_3: 'he kissed me',
  lubov_ask_place_4: 'I did not stop him',
  lubov_ask_place_date: 'What date? Exactly.',
  lubov_ask_place_inside: 'Did you go into the hotel?',
  lubov_ask_place_katya: 'What did you tell Katya at that point?',

  lubov_ask_katya_1: 'I really was at Katya’s for part of the night',
  lubov_ask_katya_2: 'then Artyom texted and I left',
  lubov_ask_katya_3: 'I told Katya I was going home',
  lubov_ask_katya_4: 'I told you I was staying with her',
  lubov_ask_katya_exact: 'Let us be clear: you prepared two different stories.',
  lubov_ask_katya_angry: 'You used your friend as an alibi.',
  lubov_ask_katya_calm: 'I will listen. Do not change another detail.',

  lubov_call_lie_1: 'I did not prepare a version',
  lubov_call_lie_2: 'I am trying to explain something that has no decent explanation',
  lubov_call_lie_3: 'there was one kiss',
  lubov_call_lie_4: 'I left afterward',
  lubov_call_lie_specific: 'Then give me the date, place, and time.',
  lubov_call_lie_repeat: 'You are lying to me right now.',
  lubov_call_lie_listen: 'Fine. I will hear this version all the way through.',

  lubov_first_questions_1: 'it was July twelfth',
  lubov_first_questions_2: 'we worked late and had dinner afterward',
  lubov_first_questions_3: 'I told you I was staying at Katya’s because I was afraid of your questions',
  lubov_first_questions_4: 'Artyom knew about our marriage from day one. that does not make any of this better',
  lubov_first_questions_5: 'yes. he knowingly agreed to it. and so did I',
  lubov_first_questions_timeline: 'What time did you text me, and what time were you with him?',
  lubov_first_questions_katya: 'Open our chat from July 12. I remember your message.',
  lubov_first_questions_married: 'Did he ask whether you were going to leave me?',
  lubov_first_questions_truth: 'The only thing you can stop now is the next lie. Start again.',

  lubov_evidence_old_message: 'This is what you sent me at 1:03 AM.',
  lubov_evidence_fourteen: 'Fourteen minutes.',
  lubov_evidence_hotel: 'And this is you at 1:17. At the entrance.',
  lubov_evidence_silence: 'Lyubov starts typing… then goes offline.',
  lubov_evidence_reply_1: 'I do not know what to say to you now',
  lubov_evidence_reply_2: 'you are right. I did not leave after the kiss',
  lubov_evidence_reply_3: 'and it was not the only time',
  lubov_evidence_count_minutes: 'You created an alibi, then walked into a hotel with him fourteen minutes later.',
  lubov_evidence_how_many: 'How many times? Give me a number, not an explanation.',
  lubov_evidence_one_kiss: 'A minute ago this was “one kiss.”',
  lubov_evidence_start_over: 'All right. Try the truth from the beginning.',

  lubov_partial_1: 'four meetings',
  lubov_partial_2: 'the first was June fourteenth. not July twelfth',
  lubov_partial_3: 'we went to the Sever twice',
  lubov_partial_4: 'the other two times were at his place',
  lubov_partial_5: 'the physical affair has lasted two months. we have been messaging longer',
  lubov_partial_6: 'I know every message is making this worse',
  lubov_partial_show_chat: 'Show me the chat. Not selected pieces—the context.',
  lubov_partial_dates_only: 'I need every date first. In order.',
  lubov_partial_no_files: 'Do not send everything. Tell me what he means to you.',
  lubov_partial_accuse: 'Four meetings do not “just happen.” You planned them.',

  lubov_chat_offer_1: 'I can show you',
  lubov_chat_offer_2: 'there is nothing graphic in it',
  lubov_chat_offer_3: 'but there are things that will hurt to read',
  lubov_chat_offer_4: 'tell me exactly what to send',
  lubov_chat_offer_all: 'The whole section around the hotel night.',
  lubov_chat_offer_dates: 'Dates and places only. No intimate messages.',
  lubov_chat_offer_last: 'The last message before you met.',
  lubov_chat_offer_refuse: 'No screenshots. I want to hear it in your words.',

  lubov_planned_chat_1: 'here. nothing cropped',
  lubov_planned_chat_attachment: 'This was several hours before the hotel.',
  lubov_planned_chat_2: 'I invented Katya in advance',
  lubov_planned_chat_3: 'so I do not get to call it an accident anymore',
  lubov_planned_chat_lie: 'You did not only cheat. You wrote the lie in advance.',
  lubov_planned_chat_hurt: 'The worst part is how calmly you prepared it.',
  lubov_planned_chat_context: 'What came before and after this section?',

  lubov_timeline_partial_1: 'we started messaging a lot on April third',
  lubov_timeline_partial_2: 'it became flirting on May second',
  lubov_timeline_partial_3: 'June fourteenth was the first time',
  lubov_timeline_partial_4: 'June twenty-eighth, July twelfth, and August second were the other three meetings',
  lubov_timeline_partial_5: 'we met again today. I meant to tell him it had to stop. I did not get that far',
  lubov_timeline_partial_forward: 'Show me one message that best explains what this was between you.',
  lubov_timeline_partial_chat: 'Now show me the context from July 12 after all.',
  lubov_timeline_partial_enough: 'I have the dates. Now answer in your own words.',

  lubov_no_chat_1: 'thank you',
  lubov_no_chat_2: 'not because there is anything left to hide after this',
  lubov_no_chat_3: 'I just do not want to turn our life into scrolling through someone else’s chat',
  lubov_no_chat_4: 'but there is one message from him you still need to see',
  lubov_no_chat_ask_feelings: 'Then tell me first: did you get attached to him?',
  lubov_no_chat_one_message: 'Show me one. The one that makes the situation clear.',
  lubov_no_chat_regret: 'Convenient that you decide what I “need” to see.',

  lubov_forward_stay_1: 'this was August second',
  lubov_forward_stay_attachment: 'He asked me after midnight.',
  lubov_forward_stay_2: 'he wanted me to stay',
  lubov_forward_stay_3: 'I did not answer immediately',
  lubov_forward_stay_answer: 'What did you answer?',
  lubov_forward_stay_meaning: 'Why is this the message that matters?',
  lubov_forward_stay_insult: 'It must have felt good choosing whose bed to sleep in.',

  lubov_forward_answer_1: 'this was my answer',
  lubov_forward_answer_attachment: 'I wrote it three minutes later.',
  lubov_forward_answer_2: '“he will notice”',
  lubov_forward_answer_3: 'as if you were not a person, just an alarm system',
  lubov_forward_answer_4: 'I feel sick reading it now',
  lubov_forward_answer_hurt: '“He will notice.” That was all I was in that conversation.',
  lubov_forward_answer_fact: 'This proves the meetings continued after the hotel.',
  lubov_forward_answer_rage: 'You came home and lay beside me afterward.',

  lubov_boundary_one_1: 'do not turn me into an object passed between two men',
  lubov_boundary_one_2: 'I cheated on you. I lied',
  lubov_boundary_one_3: 'I will answer for that',
  lubov_boundary_one_4: 'but I will not let you keep humiliating me',
  lubov_boundary_one_apologize: 'That was humiliating. I am sorry. I want answers, not a victory.',
  lubov_boundary_one_cold: 'Fine. No insults. Continue.',
  lubov_boundary_one_repeat: 'After what you did, you do not get to set boundaries.',

  lubov_full_admission_1: 'all right. the full timeline',
  lubov_full_admission_2: 'personal conversations started April 3. flirting started May 2',
  lubov_full_admission_3: 'meetings: June 14 and 28, July 12, August 2',
  lubov_full_admission_4: 'we saw each other outside the Sever today. nothing physical happened, but that does not erase the rest',
  lubov_full_admission_5: 'Katya covered for me once. then she said she would never do it again',
  lubov_full_admission_6: 'I did not use our money. Artyom paid for the hotels',
  lubov_full_admission_7: 'I chose to cheat. not Katya, not him, and not you',
  lubov_full_admission_crosscheck: 'Say that again: four meetings. You began with “one kiss.”',
  lubov_full_admission_last_chat: 'Show me the part you are still afraid to show.',
  lubov_full_admission_believe: 'At least this version does not collapse. I hear you.',
  lubov_full_admission_manipulation: 'Do not make the confession heroic. You only speak after evidence forces you.',

  lubov_timeline_crosscheck_1: 'yes. first I said “one kiss”',
  lubov_timeline_crosscheck_2: 'then I said there had been one meeting',
  lubov_timeline_crosscheck_3: 'both versions were lies',
  lubov_timeline_crosscheck_4: 'the facts now: four meetings and a two-month physical affair',
  lubov_timeline_crosscheck_5: 'there were no other meetings. I understand why you cannot take that on trust anymore',
  lubov_timeline_crosscheck_chat: 'Then show me the last hidden section. Do not choose for me.',
  lubov_timeline_crosscheck_enough: 'I have it. No new version from here.',
  lubov_timeline_crosscheck_rage: 'You released the truth in pieces until every lie broke.',

  lubov_full_chat_1: 'there is one more conversation. August eighteenth',
  lubov_full_chat_attachment: 'I was supposed to decide after this. I did not.',
  lubov_full_chat_2: 'I told you I loved you',
  lubov_full_chat_3: 'and told him I did not understand what that meant anymore',
  lubov_full_chat_4: 'that does not make my love for you fake. it does make my words cruel',
  lubov_full_chat_love: 'You loved me and kept doing this anyway?',
  lubov_full_chat_choice: 'You did not choose. You waited for someone to choose for you.',
  lubov_full_chat_caps: 'YOU DISCUSSED WHETHER YOU WOULD STAY WITH ME.',

  lubov_rage_peak_1: 'YES',
  lubov_rage_peak_2: 'YES, ALL RIGHT?!',
  lubov_rage_peak_3: 'I LIED TO YOU IN ADVANCE AND CAME HOME FOUR TIMES AS IF NOTHING HAD HAPPENED',
  lubov_rage_peak_4: 'BUT YOU LOOKED THROUGH ME FOR A YEAR',
  lubov_rage_peak_5: 'I am making this your fault again',
  lubov_rage_peak_6: 'stop. that is not fair. the distance belonged to both of us. the affair is mine',
  lubov_rage_peak_7: 'Lyubov was offline for a few seconds.',
  lubov_rage_peak_8: 'I cannot believe we are dismantling six years of marriage through messages',
  lubov_rage_peak_hurt: 'Because I cannot bear to hear your voice right now.',
  lubov_rage_peak_cold: 'This is safer. At least we are not interrupting each other.',
  lubov_rage_peak_take_responsibility: 'Yes, I pulled away. That is my part. The affair is still yours.',
  lubov_rage_peak_humiliate: 'Do not hide behind the marriage. You enjoyed living two lives.',

  lubov_boundary_two_1: 'listen carefully',
  lubov_boundary_two_2: 'I have admitted what I did',
  lubov_boundary_two_3: 'that does not give you the right to humiliate me as long as you want',
  lubov_boundary_two_4: 'one more message like that and I am ending this conversation',
  lubov_boundary_two_apologize: 'I crossed a line. I am sorry. Pain does not excuse that.',
  lubov_boundary_two_end_marriage: 'No humiliation. But our marriage may already be over.',
  lubov_boundary_two_repeat: 'Then end it. Your truth only appears under pressure anyway.',

  lubov_after_rage_1: 'I drank some water',
  lubov_after_rage_2: 'Katya is in the other room and has no idea what to say',
  lubov_after_rage_3: 'you are home alone. I am here',
  lubov_after_rage_4: 'that is why we are messaging. if we saw each other now, we would only shout',
  lubov_after_rage_5: 'ask what you genuinely need to know',
  lubov_after_rage_why: 'Why? Not “why did we drift apart.” Why did you choose an affair?',
  lubov_after_rage_love: 'Do you love him?',
  lubov_after_rage_caught: 'If I had not found out, would you have stopped?',
  lubov_after_rage_done: 'I cannot do any more. We only decide where you sleep tonight.',

  lubov_why_1: 'we almost stopped talking over the last eleven months',
  lubov_why_2: 'you came home late and shut down. I answered by doing the same',
  lubov_why_3: 'I stopped saying I was hurt because I expected silence before I even spoke',
  lubov_why_4: 'Artyom listened. he asked questions. he remembered small things',
  lubov_why_5: 'at first I only liked the attention',
  lubov_why_6: 'then I started waiting for his messages more than yours',
  lubov_why_7: 'that is an explanation. not an excuse. I chose the affair instead of demanding an honest conversation or leaving',
  lubov_why_responsibility: 'Thank you for not ending that with “you made me do it.”',
  lubov_why_not_excuse: 'The distance was real. It did not sign a permission slip for lying.',
  lubov_why_blame: 'Convenient: I did not talk enough, so you found someone who did.',

  lubov_love_question_1: 'I do not know',
  lubov_love_question_2: 'and I know that may be worse than a simple yes',
  lubov_love_question_3: 'I became attached to him',
  lubov_love_question_4: 'but I did not build a life with him. I kept holding on to ours',
  lubov_love_question_5: 'which meant betraying both of you instead of choosing',
  lubov_love_question_husband: 'Did you love me then?',
  lubov_love_question_caught: 'If it was not love, why did you keep going?',
  lubov_love_question_choose: 'Are you ready to end all contact with him?',

  lubov_loved_me_1: 'yes',
  lubov_loved_me_2: 'that is the ugliest part',
  lubov_loved_me_3: 'when I wrote “I love you,” not every message was a lie',
  lubov_loved_me_4: 'I could love you and still do what I did',
  lubov_loved_me_5: 'I am not asking you to accept that as normal. I do not understand it myself',
  lubov_loved_me_caught: 'Were you ever going to tell me yourself?',
  lubov_loved_me_choice: 'Then choose now: the marriage or a future with him.',
  lubov_loved_me_silence: 'I need a few seconds without answering.',

  lubov_artem_choice_1: 'he texted today after I left for Katya’s',
  lubov_artem_choice_2: 'I did not answer',
  lubov_artem_choice_3: 'if we decide to try, I will end all contact and write it in front of you',
  lubov_artem_choice_4: 'but I will not promise reconciliation because I am afraid of losing the apartment',
  lubov_artem_choice_cut: 'Not as a promise that I will forgive you. End it because the double life has to stop.',
  lubov_artem_choice_no_promise: 'If you are still thinking about him, do not give me another false promise.',
  lubov_artem_choice_not_my_order: 'It has to be your decision, or I am only getting words under pressure again.',

  lubov_caught_question_1: 'if you had not found out…',
  lubov_caught_question_2: 'I want to tell you I would have stopped today',
  lubov_caught_question_3: 'but that would be one more convenient version',
  lubov_caught_question_4: 'I do not know whether I would have stopped',
  lubov_caught_question_5: 'I was not planning to tell you. at least, I had no date in mind',
  lubov_caught_question_6: 'I am sorry. that is the last truth I was too afraid to make room for before tonight',
  lubov_caught_question_thanks: 'That answer is horrifying. But for once you did not make it more comfortable.',
  lubov_caught_question_late: 'Thank you for being honest. It came too late to repair anything tonight.',
  lubov_caught_question_rage: 'So you would have continued until a stranger caught you on camera.',

  lubov_tonight_1: 'what do you want me to do tonight?',
  lubov_tonight_2: 'I am at Katya’s now. I have not gone back to the apartment since I left',
  lubov_tonight_3: 'my suitcase for a few days is there, and I did not touch your things',
  lubov_tonight_4: 'I will not come back without your agreement. but it is still my home too',
  lubov_tonight_katya: 'Stay at Katya’s. We will make a calm plan tomorrow.',
  lubov_tonight_get_things: 'Collect what you need tomorrow when I am out.',
  lubov_tonight_shared_home: 'You are right: the home is shared. Stay at Katya’s tonight, and we decide together tomorrow.',
  lubov_tonight_decide: 'Decide for yourself. I cannot decide for both of us right now.',

  lubov_suitcase_1: 'I packed it before meeting Artyom. I meant to spend a few days with Katya and think',
  lubov_suitcase_attachment: 'Only clothes and essentials for a few days.',
  lubov_suitcase_2: 'this is not me trying to look decisive',
  lubov_suitcase_3: 'I just want you to know I am not going to force my way home tonight',
  lubov_suitcase_4: 'I will only collect the rest after we agree on it',
  lubov_suitcase_keys: 'Which keys do you have, and which are at home?',
  lubov_suitcase_days: 'Let this be a few days, not a final decision.',
  lubov_suitcase_throw: 'I can box up the rest of your things and put them outside tomorrow.',
  lubov_suitcase_pause: 'We are not dividing the wardrobe tonight. Apartment and money first.',

  lubov_keys_context_1: 'my set is with me',
  lubov_keys_context_2: 'the spare apartment keys and second car key are on the kitchen table',
  lubov_keys_context_3: 'I photographed them before I left',
  lubov_keys_context_4: 'you cannot change the locks without a conversation. the apartment belongs to both of us',
  lubov_keys_context_fair: 'I will not. Your things stay exactly where they are.',
  lubov_keys_context_change_locks: 'After tonight, I do not owe you access.',
  lubov_keys_context_tomorrow: 'We deal with keys tomorrow, with a witness or a lawyer.',

  lubov_property_boundary_1: 'no',
  lubov_property_boundary_2: 'you can end the marriage. you never have to forgive me',
  lubov_property_boundary_3: 'but throwing out my things or changing the locks is not a conversation. it is revenge',
  lubov_property_boundary_4: 'if we cannot speak calmly, lawyers handle everything from here',
  lubov_property_boundary_step_back: 'You are right. I will not touch your things or access.',
  lubov_property_boundary_lawyer: 'Then tomorrow everything is in writing and through a lawyer.',
  lubov_property_boundary_double: 'After your betrayal, you do not get to lecture me about revenge.',

  lubov_property_transition_1: 'we are both borrowers on the mortgage',
  lubov_property_transition_2: 'the car was bought with joint money even though it is registered to you',
  lubov_property_transition_3: 'the savings account is joint',
  lubov_property_transition_4: 'I have not withdrawn anything or paid for Artyom from it',
  lubov_property_transition_5: 'furniture, appliances, and personal things can be listed later. the apartment, debt, and money matter tonight',
  lubov_property_transition_mortgage: 'Send the mortgage statement. I need figures, not memory.',
  lubov_property_transition_money: 'Show me the joint account first. Now.',
  lubov_property_transition_lawyer: 'We collect the documents and book a lawyer tomorrow.',
  lubov_property_transition_not_tonight: 'Enough. Documents tomorrow. Tonight we only decide what happens to us.',

  lubov_mortgage_1: 'I found the current statement in our shared folder',
  lubov_mortgage_attachment: 'Both of us are borrowers. The remaining balance is inside.',
  lubov_mortgage_2: '3,870,000 rubles',
  lubov_mortgage_3: 'the monthly payment is 68,400',
  lubov_mortgage_4: 'sale, buying out a share, or keeping it as is comes after legal advice. we cannot settle that tonight',
  lubov_mortgage_list: 'Tomorrow we list the apartment, car, and account. Nothing disappears.',
  lubov_mortgage_sell: 'Selling the apartment is a real option if the marriage is over.',
  lubov_mortgage_keep: 'I can discuss buying your share after a valuation.',
  lubov_mortgage_war: 'You do not get half after what you did.',

  lubov_bank_1: 'I opened the account',
  lubov_bank_attachment: 'Current balance and transactions for the last ninety days.',
  lubov_bank_2: 'the 1,240,000 is all there',
  lubov_bank_3: 'there have been no withdrawals',
  lubov_bank_4: 'Artyom paid for the hotels. I know even that clarification sounds disgusting',
  lubov_bank_5: 'we can require both signatures on every transaction until this is settled officially',
  lubov_bank_acknowledge: 'I see it. Thank you for leaving the money alone at least.',
  lubov_bank_freeze: 'Require both approvals until we decide.',
  lubov_bank_accuse: 'A screenshot can be prepared. I will verify the statement myself.',
  lubov_bank_not_point: 'The money matters, but it is not what hurts most right now.',

  lubov_final_1: 'we reached the most frightening practical question',
  lubov_final_2: 'not who loved whom',
  lubov_final_3: 'what we do tomorrow morning',
  lubov_final_4: 'I will not demand forgiveness or promise that trust will return',
  lubov_final_5: 'give me the decision you will still be able to repeat tomorrow',
  lubov_final_divorce: 'We are getting divorced. We only need to decide how.',
  lubov_final_separate: 'We live apart. No final decision tonight.',
  lubov_final_try: 'You end all contact with Artyom. Then we try, without any promise that I will forgive you.',
  lubov_final_practical: 'We stay together for now. We cannot afford to divide the apartment and money yet.',
  lubov_final_him: 'If you will not end it with him, choose him and say it plainly.',
  lubov_final_war: 'Lawyers only from here. No private agreements.',

  lubov_divorce_tone_1: 'I understand',
  lubov_divorce_tone_2: 'then one last question: do we end as enemies, or as people who spent eight years as a family?',
  lubov_divorce_tone_3: 'the ring and spare keys are still on the table',
  lubov_divorce_tone_period: 'No more conversations. Lawyer tomorrow. This is the end.',
  lubov_divorce_tone_honest: 'An honest divorce. We document the property and do not take revenge.',
  lubov_divorce_tone_whole_truth: 'Save the entire chat and timeline first. Not one more hidden detail.',

  lubov_end_period_1: 'all right',
  lubov_end_period_attachment: 'I left the ring beside the keys.',
  lubov_end_period_2: 'tomorrow I will only send the time for the lawyer',
  lubov_end_period_3: 'goodbye',
  lubov_end_war_1: 'then there are no private agreements',
  lubov_end_war_2: 'my lawyer will contact yours. neither of us touches the property or accounts before that',
  lubov_end_war_attachment: 'The ring is on the table. Documents decide the rest.',
  lubov_end_war_3: 'I will not answer again tonight',
  lubov_end_blocked_1: 'I told you I would not continue in this tone',
  lubov_end_blocked_2: 'we will communicate about the apartment through a lawyer. do not message me here again',
  lubov_end_blocked_3: 'Lyubov is no longer accepting messages.',
  lubov_end_separate_1: 'a few days at Katya’s',
  lubov_end_separate_attachment: 'The spare keys are there. I took my own set.',
  lubov_end_separate_2: 'documents and essentials tomorrow. no decision about the marriage yet',
  lubov_end_separate_3: 'good night—if tonight can be good at all',
  lubov_end_honest_divorce_1: 'thank you. not for the divorce. for not destroying what little respect remains',
  lubov_end_honest_divorce_attachment: 'I left the ring and keys until we speak to a lawyer.',
  lubov_end_honest_divorce_2: 'I will send the document list in the morning',
  lubov_end_honest_divorce_3: 'I am sorry honesty only arrived at the end',
  lubov_end_try_again_1: 'I will write to Artyom now and tell him it is over',
  lubov_end_try_again_2: 'not as a condition of forgiveness. you may never forgive me',
  lubov_end_try_again_3: 'then we live apart for a few weeks and try counseling, if you still agree',
  lubov_end_try_again_4: 'I am not asking you to trust words tonight',
  lubov_end_try_again_5: 'only to judge the actions after it',
  lubov_end_without_trust_1: 'so we are staying because of the payment and fear of changing everything',
  lubov_end_without_trust_2: 'I will agree to that tonight',
  lubov_end_without_trust_3: 'but we both understand this is not reconciliation',
  lubov_end_without_trust_4: 'it is an apartment where trust will live behind a lock',
  lubov_end_whole_truth_1: 'I exported the entire chat and timeline',
  lubov_end_whole_truth_2: 'I deleted nothing. Katya will confirm the dates if you ask',
  lubov_end_whole_truth_attachment: 'The spare keys stay at home. I am staying at Katya’s.',
  lubov_end_whole_truth_3: 'the truth cannot return those months to you',
  lubov_end_whole_truth_4: 'but now the decision is yours, not the product of my last lie',
  lubov_end_chooses_him_1: 'I cannot promise I will end it with him',
  lubov_end_chooses_him_2: 'if I say otherwise now, it will be the exact lie that brought us here',
  lubov_end_chooses_him_attachment: 'I left the ring beside the keys.',
  lubov_end_chooses_him_3: 'I am sorry. I am choosing not to come back',

  hint_lubov_start: 'The opening sets the tone, but the photo is already sent: Lyubov never starts this conversation.',
  hint_lubov_reaction_explain: 'Her first question is about the source. Notice that she recognizes the content immediately.',
  hint_lubov_reaction_deny: 'Do not argue with the image in general; establish that Lyubov recognizes it.',
  hint_lubov_reaction_ultimatum: 'Pressure may produce speed, but a precise observation preserves the path to the whole truth.',
  hint_lubov_reaction_sarcastic: 'Sarcasm releases anger, but it can make Lyubov defend herself instead of answering.',
  hint_lubov_reaction_rage: 'Naming anger is safer than threatening. Facts will matter later.',
  hint_lubov_first_version: 'Let Lyubov commit to a date, place, or alibi before the evidence contradicts a specific claim.',
  hint_lubov_ask_man: 'Artyom’s role matters, but the point where work became personal matters more.',
  hint_lubov_ask_place: 'The place can be matched to the time on the second frame.',
  hint_lubov_ask_katya: 'Different stories for Katya and her husband reveal a prepared alibi.',
  hint_lubov_call_lie: 'An accusation is stronger when followed by a request for verifiable details.',
  hint_lubov_first_questions: 'The old message has an exact time. Compare it with the second photo.',
  hint_lubov_evidence_break: 'Fourteen minutes breaks both the alibi and the claim that nothing was planned.',
  hint_lubov_partial_admission: 'You can demand context, dates, or meaning. Full context is required for the secret path.',
  hint_lubov_chat_offer: 'The screenshot proves planning; a forwarded message later delivers a separate emotional blow.',
  hint_lubov_planned_chat: 'The evidence now proves not only an event, but the prior intent to lie.',
  hint_lubov_timeline_partial: 'Dates help, but they do not show how Lyubov described the player inside the affair.',
  hint_lubov_no_chat: 'Refusing the full screenshot keeps the talk human, but reduces the verifiable record.',
  hint_lubov_forward_stay: 'The important question is not what Artyom wrote, but what Lyubov answered.',
  hint_lubov_forward_answer: 'You can express pain sharply without humiliating another person.',
  hint_lubov_boundary_one: 'The first boundary violation can still be repaired by owning it directly.',
  hint_lubov_full_admission: 'The complete timeline must match every earlier date. Auditing the contradiction opens a fuller record.',
  hint_lubov_timeline_crosscheck: 'The changed story is proven. Decide whether you need the last hidden fragment.',
  hint_lubov_full_chat: 'This fragment answers the question about feelings without making them simple.',
  hint_lubov_rage_peak: 'Owning your part in the marriage’s distance does not mean accepting blame for the affair.',
  hint_lubov_boundary_two: 'This is the second warning. Repeated humiliation ends the chat.',
  hint_lubov_after_rage: 'After the shouting, ask one question that cannot be replaced by another date.',
  hint_lubov_why: 'An explanation is not an excuse. Watch whether Lyubov owns her choice.',
  hint_lubov_love_question: '“I do not know” is information. You can ask about her husband, the affair’s future, or no contact.',
  hint_lubov_loved_me: 'Sincere words and betrayal can coexist. That does not require forgiveness.',
  hint_lubov_artem_choice: 'A promise made under threat can become the next lie. Repair requires a voluntary end to the double life.',
  hint_lubov_caught_question: 'The most honest answer may be the most painful. Your response shapes trust in everything after it.',
  hint_lubov_tonight: 'The apartment is shared. Choosing tonight’s sleeping arrangement does not grant unilateral control of access.',
  hint_lubov_suitcase: 'The suitcase explains why Lyubov is already at Katya’s; it does not prove a planned divorce.',
  hint_lubov_keys_context: 'The spare keys and her personal set are different. Do not confuse temporary separation with ownership.',
  hint_lubov_property_boundary: 'Rejecting revenge does not mean rejecting divorce or legal protection.',
  hint_lubov_property_transition: 'Documents appear naturally only now: the emotional decision has reached joint obligations.',
  hint_lubov_mortgage: 'The figures prove the debt, not who gets the apartment. That is a separate legal question.',
  hint_lubov_bank: 'The balance removes one financial suspicion without reducing the betrayal.',
  hint_lubov_final_decision: 'The available outcomes reflect the whole night: honesty, boundaries, Artyom, and conduct around property.',
  hint_lubov_divorce_tone: 'The secret ending requires every major piece of evidence, an exact timeline, and a respectful response to late honesty.',
};
