import type { DialogueNode } from '../../../../types/dialogue';
import { camilaRuNodes } from './ru';

// The graph is language-neutral; only authored text is replaced here. Keeping IDs
// identical lets saves survive a language switch in the middle of a conversation.
const en: Record<string, string> = {
  start_warm: "Hi, Camila. I think I have your envelope. Want me to save it from my curiosity?",
  start_bold: 'You left a key under my doormat. Tell me that was intentional.',
  start_flirt: 'If this is your way of asking me out, a key is some pretty dark flirting.',
  start_careful: 'Hi. I do not want to alarm you, but there is something with your initials by my door.',
  start_risky: 'I opened the empty apartment across the hall with your key. My name is written on the wall.',
  warm_1_a: "don't open it.", warm_1_b: 'That came out harsher than I meant. Hi.',
  warm_1_c: 'Is there a blue stripe on it? And a tiny 47 in the corner?',
  warm_return: 'It is intact. I can just bring it to you.', warm_photo: 'I will not open it. I can send a photo so you can check.',
  warm_tease: 'Now “do not open it” is going to live in my head all evening.',
  warm_2_a: 'Thank you. Seriously.', warm_2_b: 'I left it at the wrong door. Apparently I have a gift for disasters today.',
  warm_2_c: 'Except I did not put my initials on it.', warm_2_d: 'Is it cold? Like it had been outside?',
  warm_notice: 'Cold, and one edge is damp. Someone brought it recently.', warm_question: 'Camila, what is in apartment 47?',
  warm_open_offer: 'If this is dangerous, say so now. I do not like being an accidental part of a plan.',
  bold_1_a: 'Under your doormat?', bold_1_b: 'I did not leave it.',
  bold_1_c: 'Show me the blade. Not the whole frame — keep the apartment number out.',
  bold_comply: 'Sent. And yes, I noticed it is older than this building.', bold_hold: 'First tell me why the number in the photo scares you.',
  bold_joke: 'No address, no fingerprints. This accomplice training is unexpectedly strict.',
  bold_2_a: '...that is it.', bold_2_b: 'The key to apartment 47. It has been empty for six years.',
  bold_2_c: 'And for two months someone has been trying to convince me that it is not.', bold_2_d: 'Did you touch it with bare hands?',
  bold_truth: 'Yes. Then I put it in a clean bag — an old work habit.', bold_lie: 'No. I am the very image of forensic discipline.',
  bold_invite: 'Come get it. You can explain why an empty apartment is sending you mail.',
  flirt_1_a: 'Dark flirting is candles in a cemetery.', flirt_1_b: 'A key under a mat is a bad day and possibly a criminal case.',
  flirt_1_c: 'Is it brass? Half-circle notch on the head?', flirt_serious: 'Yes. Jokes aside: tell me what to do with it.',
  flirt_keep: 'That is the one. A date with a criminal case still sounds intriguing.', flirt_boundary: 'It matches. I am not moving until you explain the risk.',
  flirt_2_a: 'Fine. One point for composure.', flirt_2_b: 'My sister used this key the last time she locked apartment 47.',
  flirt_2_c: 'She disappeared the next day.', flirt_2_d: 'Six years ago. So maybe no date for now, okay?',
  flirt_apology: 'I am sorry. I did not know. The key stays with me until you decide what is safe.',
  flirt_support: 'Okay. Not a date — just two adults and a strange key.', flirt_probe: 'Disappeared — or decided everyone should think so?',
  careful_1_a: 'Hi.', careful_1_b: 'First: are you inside? Is your door locked?', careful_1_c: 'Now describe it. Do not photograph the hallway.',
  careful_details: 'I am inside, door locked. Brass key, “C. M.” tag, fresh scratch.', careful_why: 'I am safe. Why did you ask about the door first?',
  careful_call: 'Everything is locked. If typing is unsafe, send one dot and I will call the police.',
  careful_2_a: 'You notice things.', careful_2_b: 'The scratch is fresh. Yesterday that key was in an evidence bag in the manager’s office.',
  careful_2_c: 'He swore he had no idea what it opened.', careful_2_d: 'Please do not call yet. I need ten minutes and someone who does not panic.',
  careful_ten: 'You have ten minutes. Then we decide together who to call.', careful_refuse: 'No. You can ask for help, but you do not get to manage my safety.',
  careful_manager: 'What is the manager’s name, and why did the key end up with me?',
  risky_1_a: 'Get out.', risky_1_b: 'Do not touch the wall. Do not turn on the light. Stay away from the window.',
  risky_1_c: 'Once you are home, type “kettle”. No jokes.', risky_leave: 'Kettle. I am home. Door locked, key with me.',
  risky_photo: 'I photographed the wall and hallway first, then left. Kettle.', risky_stay: 'No. There is a phone here frozen at 07:14. Explain.',
  risky_2_a: 'Okay. Breathing.', risky_2_b: 'Was your name printed or handwritten?', risky_2_c: 'And the date beside it — today?',
  risky_2_d: 'Your answer tells me whether one person is lying to me or two.',
  risky_exact: 'Marker. Neat handwriting, yesterday’s date. And 07:14 appears twice.',
  risky_copy: 'I recorded everything. The copy is off my phone, so it cannot quietly disappear.',
  risky_accuse: 'First tell me how you knew about the date. You expected me to go in, did you not?',
  crossing_warm: 'You could have pretended you saw nothing. Thank you for writing.',
  crossing_bold: 'I hate admitting it, but your tone is more useful than my panic right now.',
  crossing_flirt: 'And if we survive tonight, I may reconsider that date.',
  crossing_careful: 'You are the only person today who asked whether this was safe, not what was inside. I noticed.',
  crossing_risky: 'You have already seen too much. Half-answers will only make this worse.',
  crossing_a: 'Apartment 47 belonged to my sister, Alina. She was 34 when she disappeared.',
  crossing_b: 'She studied how people decide under pressure. Not university research. Private.',
  crossing_c: 'At 10:40, meet me between floors six and seven. No cameras there.',
  crossing_meet: 'I will come. If you hide one more thing, I leave.', crossing_copy: 'Send me what must not disappear if you do not show up.',
  crossing_police: 'I will come, but a friend already has my location and the meeting time.',
  crossing_wait: 'No. You come to my door, stay in the hall, and explain everything.',
  stairwell_status: 'Camila is online', stairwell_a: 'I am here. Gray coat, paper cup, deeply unconvincing calm.',
  stairwell_b: 'Do not approach yet. Man in a blue jacket one flight down.', stairwell_c: 'That is Mark, the building manager. The one who had the key.',
  stairwell_d: 'He is pretending to fix a sensor that was removed in May.',
  stairs_observe: 'Let him think I do not know you. I will walk past and watch him.', stairs_confront: 'I will ask about the light like a tenant. Stay hidden.',
  stairs_retreat: 'No heroics. Separate stairs, then we talk from our apartments.', stairs_signal: 'Drop the cup. If he looks at me first, he was waiting for me.',
  threshold_a: 'He is gone.', threshold_observe: 'And he did not look at me. He looked at your door.',
  threshold_test: 'You were right. The cup was still falling and he was already looking at you.',
  threshold_spoke: '“Checking the light.” In a building with automatic fault logs. Charming man.',
  threshold_b: 'I opened the envelope. Inside is a photo of apartment 47 taken this morning.',
  threshold_c: 'A table. A folder with your name on it.', threshold_d: 'The bad part: the note on the back looks like Alina’s handwriting.',
  threshold_alina: 'Then we test the theory that Alina is alive first.', threshold_camila: 'Or you forged it to keep me involved. Did you have the chance?',
  threshold_metadata: 'A paper print came from a digital source. Check reflections, time, camera model.',
  threshold_leave: 'My file is the line. I will preserve evidence, but I am not going inside.',
  archive_status: '10:58 PM · apartment 47', archive_a: 'I am inside anyway. Do not yell — the door was already open.',
  archive_boundary: 'And yes, I remember you asked for no improvising. You may yell.',
  archive_b: 'The files are here. Twelve names. Chats, routes, reactions to staged “accidents.”',
  archive_c: 'Yours begins the day you answered the apartment listing.',
  archive_d: 'Margin note: “resists urgency; reacts to injustice.” Sound like you?',
  archive_save: 'Photograph every page and upload copies now. We can be angry later.',
  archive_privacy: 'Do not read the others. Take mine, the name list, and proof of surveillance.',
  archive_read: 'Find your own file. If this was an experiment, you might be a subject too.',
  archive_destroy: 'These files endanger all twelve. Record the covers, then destroy the contents.',
  recording_a: 'Found a recorder.', recording_b: 'One clip. Alina says: “If Camila brought the thirteenth, she chose for someone again.”',
  recording_c: 'The thirteenth is you.', recording_d: 'I need to tell you something before the recording does.',
  recording_e: 'I knew your file existed. Not everything in it. But I knew.',
  recording_silence: 'Go on. I will listen without interrupting.', recording_angry: 'You planted the key to test my reaction. Not Mark. You.',
  recording_fact: 'What exactly did you know before tonight? No polished version.', recording_time: 'First tell me why the phone was frozen at 07:14.',
  interlude_deleted: 'Camila deleted a message', interlude_a: 'I did not find you by accident.',
  interlude_b: 'Three months ago you exposed a fake fundraiser in the building chat. Calmly, with evidence, no mob.',
  interlude_c: 'Alina chose people moved by fear or flattery. You did not fit her model.',
  interlude_d: 'I moved your rental application to the top. I thought you would notice the surveillance and help prove it.',
  interlude_e: 'I left the key. Not the envelope.',
  interlude_accept_fact: 'You could have asked. Manipulation does not become care because the goal is good.',
  interlude_empathy: 'You were looking for your sister and went too far. I understand why, not how.',
  interlude_flirt_hurt: 'So even our almost-date was part of the test?', interlude_leave: 'Save the evidence. Then never write to me again.',
  midnight_status_off: 'Camila is offline', midnight_pause: 'pause', midnight_status_on: 'Camila is online',
  midnight_a: 'Someone is in the hallway.', midnight_b: 'Not Mark. Lighter steps.',
  midnight_c: 'A note slid under the door: “The second room cannot be locked from outside.”',
  midnight_d: 'Alina’s phrase. She used it for someone else’s memory.',
  midnight_call: 'Call emergency services. Do not open. I will stay on and log the time.',
  midnight_camera: 'Use your phone camera around the corner without showing yourself.',
  midnight_code: 'Reply under the door: “07:14.” If it is Alina, she will know.',
  midnight_go: 'I am coming. Do not open even for me until I name the key’s color.',
  second_a: 'The note was pinned to the back of an old photo.', second_b: 'Alina and me. I am 25, she is 34. One week before she vanished.',
  second_c: 'Today’s date on the back, and: “Ask the thirteenth what they saved.”',
  second_saved: 'It must mean your copy. Someone knows it exists.', second_none: 'If we saved nothing, she is leading us to an empty space.',
  second_d: 'Be honest: do you still have a copy of the wall, key, or files?',
  second_share: 'Yes. Encrypted. Police get it now; you get it after you are out.', second_lie_copy: 'No. Nothing survived.',
  second_admit_none: 'No, and that now looks like our worst mistake.', second_question: 'I do. But why speak to me through you if the author is nearby?',
  fracture_lie: 'Wait. You said there was no copy. Earlier you deliberately moved it off your phone.',
  fracture_key_lie: 'And the key photo shows your fingers. You said you never touched it.',
  fracture_a: 'I replayed Alina’s recording. There is a splice after “thirteenth.”',
  fracture_b: 'A tram rings in the background. That line closed a year before she vanished.',
  fracture_c: 'The recording is new, assembled from old fragments.', fracture_d: 'Mark could do that. But how did he know our childhood phrase?',
  fracture_bluff: 'From you. You are testing whether I catch the mismatch. Stop. Show the source file.',
  fracture_mark: 'Mark had the apartment and archives. We check his devices first.',
  fracture_alina: 'Alina is alive and watching whether you choose for me.',
  fracture_stop: 'I do not care who made it. I am leaving the game and giving everything to police.',
  mark_deleted: 'Message deleted', mark_a: 'Mark wrote: “Return the key and the thirteenth file. The rest is not yours.”',
  mark_b: 'He sent a photo of my door. Taken a minute ago.', mark_c: 'But the peephole reflection shows a red scarf.',
  mark_d: 'Mark wore blue. Alina wore a red scarf.', mark_e: 'I badly want to open the door. Say something sensible.',
  mark_police: 'Sensible: do not open. Police are coming; they have the photo and chat.',
  mark_choice: 'Your decision. But ask yourself: would Alina ask for the key, or ask you to choose?',
  mark_trap: 'Say the key is in 47. Make whoever it is move away from your door.',
  mark_open: 'Open on the chain and record. Sometimes the only exit is to finish the scene.',
  after_a: 'I did not open.', after_choice: 'Because for once it was my decision, not an instruction.',
  after_b: 'They left. The elevator camera caught a red scarf and a left hand.', after_c: 'A scar on it. Alina had none. Mark does.',
  after_d: 'The scarf was bait. He wanted me to open.', after_e: 'I found the last page in the file. My signature.',
  after_f: 'Six years ago I helped Alina sort applications. I called it “participant safety.” A very useful phrase.',
  after_accountability: 'Then help all twelve learn the truth. Do not waste time defending yourself.',
  after_stay: 'You were part of it. Today you can still choose how it ends.',
  after_distance: 'I will help finish this. Afterward, there will be distance between us.',
  after_condemn: 'You are no better than Alina or Mark. Your version just sounds nicer.',
  reckoning_a: 'Mark has been detained. They found a server and original forms in his storage.',
  reckoning_b: 'Nothing from Alina after she vanished. Just automated letters and edited clips.',
  reckoning_0714: 'But 07:14 is the time a ticket was bought in her name — two years after she vanished.',
  reckoning_c: 'The investigator wants us there in the morning. Separately.',
  reckoning_d: 'Four hours until morning. One question I have no right to phrase for you.', reckoning_e: 'What happens to us after this chat?',
  reckoning_honest: 'Statements first. Then coffee and one honest conversation without riddles.',
  reckoning_partners: 'We find Alina and warn the others. Personal things can wait.',
  reckoning_end: 'After the statements — nothing. But I do not regret answering.',
  reckoning_secret: 'Check the 07:14 ticket. The red scarf distracted from the left hand — and Alina’s photo is mirrored.',
  decision_secret: 'You are right. In the original the scar is on the right. At my door it was a reflection — also right. Not Mark.',
  decision_secret_2: 'I found the ticket number. A small station near Lake Baikal. Morning train arrives at 07:14.',
  decision_good: 'Strange thing: for once I am not trying to predict your answer.',
  decision_low: 'We reached the truth by different roads. We do not have to keep sharing one.',
  decision_a: 'I will not delete this chat. Even the parts I want to.', decision_b: 'Your move. Last one tonight.',
  final_secret: 'Meet at the station at 06:40. If it is Alina, you decide whether to speak to her.',
  final_dawn: 'Do not delete it. We meet dawn, give statements, then try trust without hints.',
  final_equal: 'Coffee, yes. Keys, tests, and choosing for others stay in this night.',
  final_truth: 'I trust the evidence, not you. Maybe that changes someday.',
  final_erased: 'Let the archive vanish. Sometimes safety matters more than someone else’s truth.',
  final_block: 'Delete it. Never turn me into a participant in your game again.', final_archive: 'Keep the chat for investigators. This is goodbye, Camila.',
  egd_a: 'Deal.', egd_b: 'And thank you for giving my choices back to me every time.', egd_c: 'I am outside. No keys. Two coffees.', egd_s: 'Story complete',
  ege_a: 'Fair.', ege_b: 'Then simple facts: I am 31, I hate voice notes, and I genuinely want coffee with you.', ege_c: 'This is not a test.)', ege_s: 'Story complete',
  ena_a: 'Understood.', ena_b: 'The investigator has the file. Your name will be removed from the others’ copies.', ena_c: 'Take care.', ena_s: 'Story complete',
  ent_a: 'I will not argue.', ent_b: 'Trust is not something a correct sentence can earn. Especially from me.', ent_c: 'If that ever changes, you have my number.', ent_s: 'Story complete',
  ebe_a: 'I did what you said.', ebe_b: 'The files burned. Mark’s server was empty.', ebe_c: 'He walked free a day later. By morning, apartment 47 was locked again.', ebe_s: 'Camila never came online again.',
  ebb_a: 'Maybe you are right.', ebb_b: 'But I do not want you inside this story anymore. Or mine.', ebb_s: 'Camila no longer accepts messages.', ebb_s2: 'You have been blocked.',
  es_status: '07:14 · Slyudyanka station', es_a: 'She is here.', es_b: 'Gray streak, red scarf. Alive.',
  es_c: 'Alina left the envelope so I would finally ask for help instead of selecting a helper.',
  es_d: 'I do not know if I can forgive her. For once, that decision is really mine.', es_e: 'Are you here?', es_s: 'Secret ending unlocked',
};

function translate(id: string, fallback: string | undefined): string {
  const value = en[id];
  if (!value) throw new Error(`[ContentValidator] Missing English text for ${id}: ${fallback ?? ''}`);
  return value;
}

export const camilaEnNodes: DialogueNode[] = camilaRuNodes.map((node) => ({
  ...node,
  messages: node.messages.map((message) => ({
    ...message,
    text: translate(message.id, message.text),
  })),
  choices: node.choices?.map((choice) => ({
    ...choice,
    text: translate(choice.id, choice.text),
  })),
}));
