import type { DialogueNode } from '../../../../types/dialogue';
import { camilaRuNodes } from './ru';

// The graph and development scene context are language-neutral. Only authored
// text is adapted here, so switching languages never changes story state.
const en: Record<string, string> = {
  start_warm: 'Hi, Camila. There is a blue envelope with your initials outside my door. Is it yours?',
  start_bold: 'A key marked 47 fell out of the envelope by my door. Did you leave it?',
  start_flirt: 'If a key in a blue envelope is your way of asking me out, your flirting is pretty dark.',
  start_careful: 'Hi. I do not want to alarm you, but there is an envelope with your initials under my mat and something metal inside.',
  start_risky: 'The key from your envelope opened the empty apartment across from me. Number 47. My name is on the wall, and I am still inside.',

  warm_1_a: 'hi. do not open it yet, okay?',
  warm_1_b: 'I am still at the workshop. At least half an hour from home.',
  warm_1_c: 'Blue stripe, tiny 47 in the corner?',
  warm_return: 'Yes. It is intact. I will take it inside and give it to you when you get back.',
  warm_photo: 'That is the one. I will not open it, but I can send photos of both sides.',
  warm_tease: 'That is it. Now “do not open it” is going to live in my head all evening 😅',
  warm_2_a: 'thank you. seriously',
  warm_2_b: 'Except I do not buy envelopes like that, and I did not write my initials on it.',
  warm_2_c: 'Without opening it: does it feel like one metal object inside?',
  warm_2_d: 'And is one edge damp? I have been indoors all day.',
  warm_notice: 'Yes: one object, cold envelope, damp edge. Someone brought it recently.',
  warm_question: 'One object. But tell me plainly first: what is connected to apartment 47?',
  warm_open_offer: 'If this is dangerous, say so now. I will help, but I will not become an accidental part of someone else’s plan.',

  bold_1_a: 'Under your mat? I did not put it there.',
  bold_1_b: 'I am still at the workshop, so this is not me mixing up the doors.',
  bold_1_c: 'Photograph just the blade and tag. Keep your apartment number out of frame.',
  bold_comply: 'Sent a close-up. The tag says 47, and the key is clearly older than the new door.',
  bold_hold: 'First tell me why your first thought was my address and the camera.',
  bold_joke: 'No address, no fingerprints. This accomplice training is unexpectedly strict.',
  bold_2_a: '...yes. that is it',
  bold_2_b: 'The key to apartment 47. It is across from you and has been empty for six years.',
  bold_2_c: 'Yesterday it was sealed in a bag in the building manager’s office. Today it is with you.',
  bold_2_d: 'Did you touch it with bare hands? I am not scolding you. I need to know.',
  bold_truth: 'Yes. Then I put it in a clean bag — an old work habit.',
  bold_lie: 'No. I am the very image of forensic discipline.',
  bold_invite: 'The key is secured. When you get back, explain why an empty apartment is sending me envelopes.',

  flirt_1_a: 'Dark flirting is candles in a cemetery 😏',
  flirt_1_b: 'A key to someone else’s apartment is when the jokes stop.',
  flirt_1_c: 'Brass? Half-circle notch on the head?',
  flirt_serious: 'Yes. Jokes are off. Tell me what to do with it while you are away.',
  flirt_keep: 'That is the one. A date with a criminal case still sounds intriguing.',
  flirt_boundary: 'It matches. I am staying home, and you are telling me what the risk is.',
  flirt_2_a: 'Fine. One point for knowing when to get serious 😏',
  flirt_2_b: 'My sister Alina used this key the last time she locked apartment 47.',
  flirt_2_c: 'She disappeared the next day.',
  flirt_2_d: 'Six years ago. So no date for now, okay?',
  flirt_apology: 'I am sorry. I did not know. The key stays bagged until we decide what is safe.',
  flirt_support: 'Okay. Right now we are just two adults, one strange key, and a lot of questions.',
  flirt_probe: 'Did she vanish on her own, or did someone help her disappear?',

  careful_1_a: 'Hi.',
  careful_1_b: 'First: are you inside, and is your door locked?',
  careful_1_c: 'I am at the workshop. Describe it, but do not photograph the hall or your door number.',
  careful_details: 'I am inside, door locked. Brass key, tag marked 47, fresh scratch near the blade.',
  careful_why: 'I am safe. Why was the door your first question?',
  careful_call: 'Everything is locked. If typing becomes unsafe, send one dot and I will call for help.',
  careful_2_a: 'You notice things.',
  careful_2_b: 'That scratch is fresh. Yesterday the key was in a sealed bag in the manager’s office.',
  careful_2_c: 'His name is Mark. He claimed he had no idea what it opened.',
  careful_2_d: 'I am heading home. Give me half an hour and do not go anywhere yet.',
  careful_ten: 'Okay. Text from the car and again when you enter the building. Then we decide who to call.',
  careful_refuse: 'I will help, but you do not get to manage my safety. Staying home is my decision.',
  careful_manager: 'Why did Mark have the key, and why did it end up under my door?',

  risky_1_a: 'Get out. Now.',
  risky_1_b: 'I am at the workshop and cannot reach you quickly. Do not touch the wall or go near the window.',
  risky_1_c: 'Go back to your apartment, lock the door, and type “kettle.” No jokes.',
  risky_leave: 'Kettle. I am home, door locked, key bagged.',
  risky_photo: 'I photographed only the wall and table, then left. Kettle. The copy is safe.',
  risky_stay: 'I stayed long enough to photograph the old phone, then went home. Its screen shows 07:14. Why does that matter?',
  risky_2_a: 'Okay. Now I can breathe.',
  risky_2_b: 'Was the name printed or handwritten?',
  risky_2_c: 'Was there a date beside it? Just the fact, no theory.',
  risky_2_d: 'I am trying to work out who entered today.',
  risky_exact: 'I am home. Marker, yesterday’s date. 07:14 appears on both the phone and a note.',
  risky_copy: 'I am home. I recorded everything and moved the copy off my phone. It cannot quietly disappear.',
  risky_accuse: 'I am home. But you understood the danger too quickly. What did you know about 47 before I wrote?',

  crossing_warm: 'You could have shut the door and forgotten it. Thank you for writing.',
  crossing_bold: 'I hate admitting it, but your directness is more useful than my panic right now.',
  crossing_flirt: 'And if we get through tonight calmly, I will return to that coffee conversation 👀',
  crossing_careful: 'You asked about safety before asking what was inside. I noticed.',
  crossing_risky: 'You have already seen 47 from the inside. Half-answers will only make this worse.',
  crossing_a: 'Apartment 47 belonged to my sister Alina. She disappeared six years ago.',
  crossing_b: 'Mark manages the building. He had the key yesterday, and he was the last person to see Alina in this building.',
  crossing_c: 'I just left the workshop. About thirty minutes home. You stay inside; I will go to my apartment first, then check the stairs. We keep texting.',
  crossing_meet: 'I am staying home. Text from the entrance, and do not approach 47 until we know where Mark is.',
  crossing_copy: 'Before the drive, send the car number and whatever must survive if the connection drops.',
  crossing_police: 'I am staying home, and a friend gets your live location and arrival time. Insurance, not surveillance.',
  crossing_wait: 'Go straight to your apartment and lock the door. No one-on-one conversation with Mark.',

  stairwell_status: '10:18 PM · Camila is between floors six and seven',
  stairwell_a: 'I am in the building. Are you inside? Do not come out.',
  stairwell_b: 'One floor above me. Man in a blue jacket outside 47.',
  stairwell_c: 'That is Mark, the building manager. The one who had the key. Long pale scar across his left hand.',
  stairwell_d: 'He is pretending to fix a sensor. That sensor was removed in May.',
  stairs_observe: 'Do not follow him. From cover, note the time and what he is carrying, then go home.',
  stairs_confront: 'Call him as a tenant and ask about the lights. Stay hidden — let us hear which story he uses.',
  stairs_retreat: 'Do not test him alone. Go home, lock the door, and keep talking from there.',
  stairs_signal: 'If you can do it from cover, drop the cup and see where he looks first. Then go straight home.',

  threshold_a: 'I am home. Door locked. Mark went downstairs.',
  threshold_observe: 'Before leaving, he photographed your door. I saw the screen.',
  threshold_test: 'The cup was still falling when he looked at your door. He was waiting for your reaction.',
  threshold_spoke: 'On the phone he said he was checking the lights. The automatic fault log is empty.',
  threshold_retreat: 'You were right about retreating. I think much better behind a locked door than on those stairs.',
  threshold_b: 'There is a second blue envelope under my door. It was not here when I left.',
  threshold_c: 'Inside: a fresh photo of open apartment 47. A folder with your name on the table.',
  threshold_d: 'On the back: “Alina, personal.” The handwriting looks like hers.',
  threshold_alina: 'Assume Alina may be alive. But first preserve the envelope and call emergency services: someone visited both doors.',
  threshold_camila: 'Other than you and Mark, who knew about the key, Alina, and both our doors?',
  threshold_metadata: 'Photograph the print and its back in detail. Time, reflections, and paper may identify the source.',
  threshold_leave: 'Do not enter 47. Bag the envelope, stay behind your locked door, and wait for help.',

  archive_status: '10:36 PM · Camila is outside apartment 47',
  archive_called: 'Emergency services have the address. No unit is assigned yet; the operator told me not to enter.',
  archive_waited: 'I called emergency services. They logged the address, but there is no free unit yet.',
  archive_a: 'I went up only to photograph the open door. Through the gap I saw a folder marked “Alina M.” and an access sheet with Mark’s name. The door started closing, so I went in. My decision.',
  archive_boundary: 'I know you asked me not to improvise. I left the door open and kept my phone in my hand.',
  archive_b: 'Twelve folders. Names, pieces of chats, routes, reactions to staged events.',
  archive_c: 'Yours starts the day you answered the apartment listing.',
  archive_d: 'Margin note: “resists urgency; reacts to injustice.” Someone was watching before tonight.',
  archive_save: 'Photograph pages with names, dates, and Mark’s access. Send copies immediately, then get out.',
  archive_privacy: 'Do not read private chats. We need the name list, my file, and proof of surveillance.',
  archive_read: 'Check the folder with your name. Alina may have been watching you too.',
  archive_destroy: 'If those are real addresses, preserve the covers and access log, then destroy the route pages.',

  recording_a: 'I am taking Alina’s folder, the name list, and the access log. Leaving the rest.',
  recording_b: 'Small recorder in Alina’s folder. One clip, her voice: “If Camila brought the thirteenth, she chose for someone again.”',
  recording_c: 'The thirteenth is you.',
  recording_d: 'I am leaving 47. But before the recording says the rest, I need to say it myself.',
  recording_e: 'I knew your file existed. Not what was inside, but I knew about it.',
  recording_silence: 'Get out and lock your own door first. Then tell me everything. I will listen.',
  recording_angry: 'You knew about the file and gave me the key. Was this a test of my reaction?',
  recording_fact: 'What exactly did you know before tonight? Facts only.',
  recording_time: 'And why does 07:14 appear twice in 47? Did you know about it?',

  interlude_deleted: 'Camila deleted a message',
  interlude_a: 'I am out and locked inside my apartment. The deleted line was: “I am scared I became like Alina.” Because it is true.',
  interlude_b: 'Three months ago you exposed a fake fundraiser in the building chat. Calmly, with evidence, no mob.',
  interlude_c: 'Alina selected people she could move with fear or flattery. You did not fit her pattern.',
  interlude_d: 'I moved your rental application to the top. I hoped you would spot the surveillance and help prove it.',
  interlude_e: 'I put the key under your mat. The blue envelopes were not mine.',
  interlude_accept_fact: 'You could have asked. A good goal does not turn manipulation into care.',
  interlude_empathy: 'You were looking for your sister and went too far. I understand why, not how.',
  interlude_flirt_hurt: 'So even the coffee conversation was part of the test?',
  interlude_leave: 'Give the evidence to the police. After that, do not write to me again.',

  midnight_status_off: 'Camila is offline',
  midnight_pause: 'pause',
  midnight_status_on: 'Camila is back online',
  midnight_a: 'someone is standing outside my door',
  midnight_b: 'No knock. Just a shadow through the peephole. I am not opening.',
  midnight_c: 'They pushed a note underneath: “The second room cannot be locked from outside.”',
  midnight_d: 'Alina’s phrase. When we were children, she used it to mean memory.',
  midnight_call: 'Call emergency services and do not open. I will stay in chat and log every message time.',
  midnight_camera: 'If you can keep your distance, place a recording phone opposite the peephole. Do not touch the lock.',
  midnight_code: 'Write “07:14” on paper and slide it under the door. Do not answer aloud or open.',
  midnight_go: 'Put me on speaker and move to the far room. I will not come over: two locked doors are safer right now.',

  second_a: 'They left. The note was attached to an old photo.',
  second_b: 'Alina and me, one week before she vanished. Red scarf, small burn mark on her right hand.',
  second_c: 'Today’s date on the back, and: “Ask the thirteenth what they saved.”',
  second_saved: 'The author knows about your copy. Someone watched what we did tonight.',
  second_none: 'If there are no copies, the only evidence left is the paper with me.',
  second_d: 'Be honest: do you still have a photo of the wall, key, or pages?',
  second_share: 'Yes, encrypted. I will send it to the police now and to you after they confirm receipt.',
  second_lie_copy: 'No. Nothing survived.',
  second_admit_none: 'No, and that now looks like our biggest mistake.',
  second_question: 'I have a copy. But how did the author know you would immediately ask me for it?',

  fracture_lie: 'Wait. You just said there was no copy. Earlier you deliberately moved it off your phone.',
  fracture_key_lie: 'And your fingers are visible in the first key photo. You said you never touched it.',
  fracture_a: 'I listened again. There is a splice right after “thirteenth.”',
  fracture_b: 'An old tram bell in the background. That route closed a year before Alina vanished.',
  fracture_c: 'The clip was assembled recently from older recordings.',
  fracture_d: 'The log I took shows Mark’s key opening 47 for the last three nights. Today at 07:14.',
  fracture_bluff: 'Stop guessing the author. Send the original audio and uncropped note photo. We check the splice and reflections.',
  fracture_mark: 'Mark had the apartment, archive, and old recordings. His devices are the first thing to check.',
  fracture_alina: 'Mark may not know that childhood phrase. Alina could be alive, but it is only a theory.',
  fracture_stop: 'Whoever did this, we stop following their script. Everything goes to the police.',

  mark_deleted: 'Camila deleted a message',
  mark_a: 'From Mark’s number: “Return the key and the thirteenth file. The rest is not yours.”',
  mark_b: 'Then a photo of my door, taken a minute ago. I called emergency services immediately; a unit is entering from the yard.',
  mark_c: 'A red scarf reflected in the peephole.',
  mark_d: 'Mark wore blue. Alina wore red, but the scarf could be bait.',
  mark_e: 'I want to open the door and end this uncertainty. Say something sensible.',
  mark_police: 'Sensible: do not open. Send the operator the full chat and your location. I will send my copy.',
  mark_choice: 'Your decision. But you can open later; you cannot close the consequences afterward.',
  mark_trap: 'Say the key is still in 47. If they go there, the camera gets their route while you stay behind the door.',
  mark_open: 'If you still choose to speak, keep the chain on and record. Waiting for help is safer.',

  after_a: 'I did not open.',
  after_choice: 'Because for once tonight I decided for myself instead of carrying out someone else’s instruction.',
  after_police: 'Emergency services already had the photo. They told me to stay away from the door and sent another unit to the service entrance.',
  after_trap: 'I wrote that the key was in 47. A minute later they headed for the stairs; the camera kept the route.',
  after_open: 'I almost touched the chain, then saw someone test the handle from outside. No. You do not open that.',
  after_b: 'The elevator camera caught a red scarf and one hand. Mirrored image, too dark.',
  after_c: 'Mark’s scar is on his left hand. The mark in the image looks right-sided, but the reflection makes it uncertain.',
  after_d: 'They headed toward the service stairs. Police are inside the building now.',
  after_e: 'I checked the last sheet I carried out of 47. My signature is at the bottom.',
  after_f: 'Six years ago I helped Alina sort applications. She called it “participant safety.” I did not ask enough questions.',
  after_accountability: 'Then do not defend yourself. Help all twelve people learn what happened to their data.',
  after_stay: 'You were part of the beginning. You can still be part of an honest ending.',
  after_distance: 'I will help through the statements. After that, there will be distance between us.',
  after_condemn: 'You knew enough to stop, but still chose me without asking. I cannot forget that.',

  reckoning_time: '1:26 AM · more than an hour later',
  reckoning_a: 'Mark was detained by the service room. He had a second key; police found a server and original forms in storage.',
  reckoning_b: 'The server has edits and automated messages sent after Alina vanished. No new recording of her.',
  reckoning_0714: 'But 07:14 was the purchase time on a ticket in Alina’s name, two years after she disappeared.',
  reckoning_c: 'The investigator wants us at nine. Separately, so our statements stay independent.',
  reckoning_d: 'A few hours until morning. One question I have no right to phrase for you.',
  reckoning_e: 'What happens to us after this chat?',
  reckoning_honest: 'Statements first. Then, if we both want it, coffee and one conversation without riddles.',
  reckoning_partners: 'We warn the others and learn what happened to Alina first. Personal things can wait.',
  reckoning_end: 'After the statements — nothing. But I do not regret answering you tonight.',
  reckoning_secret: 'Send the original door frame and old photo of Alina. A mirrored image may have swapped the hands.',

  decision_secret: 'You are right. After correcting the image, the mark is on the person’s right hand. Mark’s scar is left. It was not him.',
  decision_secret_2: 'The old photo shows a small burn on Alina’s right hand. Her ticket leads to a station by Lake Baikal; the train arrives at 07:14.',
  decision_good: 'You know what is strange? For once I am not trying to predict your answer.',
  decision_low: 'We reached the facts by different roads. We do not have to keep sharing one.',
  decision_a: 'I will preserve this chat for the investigation, even the parts I want to erase.',
  decision_b: 'Your move. Last one tonight.',
  final_secret: 'We meet for the first time at the station at 6:40. If it is Alina, you decide whether to speak to her.',
  final_dawn: 'Do not delete it. We give statements, then meet for the first time outside — no tests.',
  final_equal: 'Coffee, yes. Keys, tests, and choosing for someone else stay in this night.',
  final_truth: 'I trust the evidence, not you. Maybe that changes someday.',
  final_erased: 'We delete the dangerous pages. Sometimes people’s safety matters more than a complete archive.',
  final_block: 'Delete my number after the statements. I will not be part of your decisions again.',
  final_archive: 'Keep the chat for investigators. This is where our conversation ends, Camila.',

  egd_a: 'deal 🙂',
  egd_b: 'After a night like that, two coffees are less romance and more first aid 😅',
  egd_c: 'I am outside. No keys. Two cups. Coming down?',
  egd_s: 'Story complete',
  ege_a: 'Fair.',
  ege_b: 'Then no tests: I am 31, I hate voice notes, and I genuinely want coffee with you.',
  ege_c: 'I am outside. This is not a test 😅',
  ege_s: 'Story complete',
  ena_a: 'Understood.',
  ena_b: 'The investigator has the files. Other people’s names will be protected in case copies.',
  ena_c: 'Thank you for seeing it through. Take care.',
  ena_s: 'Story complete',
  ent_a: 'I will not argue.',
  ent_b: 'One correct sentence cannot earn trust. Not after what I did.',
  ent_c: 'If that ever changes, you have my number.',
  ent_s: 'Story complete',
  ebe_a: 'I destroyed the route pages, like we decided.',
  ebe_b: 'Without them, police could not connect the server to specific people.',
  ebe_c: 'Mark was released. By morning, 47 was locked again. I cannot continue this conversation.',
  ebe_s: 'Camila never came online again.',
  ebb_a: 'All night I asked for my right to decide. You answered as if you had already passed sentence.',
  ebb_b: 'Do not advise me anymore. I will handle this myself.',
  ebb_s: 'Camila no longer accepts messages.',
  ebb_s2: 'You have been blocked.',
  es_status: '7:14 AM · Slyudyanka station',
  es_a: 'I see you. And her.',
  es_b: 'Gray streak, red scarf, burn on her right hand. Alina is alive.',
  es_c: 'She admitted it: she left the envelopes. She wanted me to ask for help instead of selecting a helper.',
  es_d: 'I do not know if I can forgive her. But the decision will be mine.',
  es_e: 'Stay with me, okay?',
  es_s: 'Secret ending unlocked',
};

function translate(id: string, fallback: string | undefined): string {
  const value = en[id];
  if (!value) throw new Error(`[ContentValidator] Missing English text for ${id}: ${fallback ?? ''}`);
  return value;
}

export const camilaEnNodes: DialogueNode[] = camilaRuNodes.map((node) => ({
  ...node,
  messages: node.messages.map((message) => ({
    ...message,
    text: translate(message.id, message.text),
  })),
  choices: node.choices?.map((choice) => ({
    ...choice,
    text: translate(choice.id, choice.text),
  })),
}));
