import type { DialogueNode } from '../../../../types/dialogue';
import { leraRuNodes } from './ru';

const messageText: Record<string, string> = {
  lera_calm_a: 'can\'t sleep',
  lera_calm_b: 'and you actually texted 🙂',
  lera_ironic_a: 'only one',
  lera_ironic_b: 'you\'ll have to earn the rest 🙃',
  lera_confident_a: 'observant',
  lera_confident_b: 'or overconfident. I haven\'t decided yet 😏',
  lera_flirt_a: 'suspiciously good?',
  lera_flirt_b: 'that is a terrible compliment',
  lera_flirt_c: '...and somehow it works 🤭',
  lera_risky_a: 'oh. straight to the interrogation',
  lera_risky_b: 'maybe I wanted to see whether you would text at all',
  lera_check_calm: 'okay. we can just talk',
  lera_check_ironic: 'fine. I\'m spending my one honest question on you',
  lera_check_confident: 'let\'s test that eye for detail',
  lera_check_flirty: 'if the compliment worked, we may as well continue 😏',
  lera_check_risky: 'no interrogation, then',
  lera_check_a: 'why did you text right now?',
  lera_check_b: 'not during the day. not right after Nadia. after midnight',
  lera_check_c: 'no polished version',
  lera_truth_lie: 'no. “I just tapped it” really doesn\'t suit you 🤨',
  lera_truth_a: 'then a small test',
  lera_truth_b: 'I can choose not to answer. so can you',
  lera_truth_c: 'and nobody argues with “no.” deal?',
  lera_respect_a: 'good answer',
  lera_respect_b: 'I just got home',
  lera_respect_c: 'and finally changed 😅',
  lera_play_a: 'teasing is allowed',
  lera_play_b: 'demanding isn\'t. can you tell the difference?',
  lera_pressure_a: 'stop',
  lera_pressure_b: 'you\'re asking me to prove I\'m interested',
  lera_pressure_c: 'I don\'t play that game',
  lera_no_photo_a: 'that is exactly what I was testing',
  lera_no_photo_b: 'most people hear “I changed” and ask for a photo',
  lera_no_photo_c: 'you didn\'t',
  lera_photo_preface: 'I\'m not rushing',
  lera_photo_bridge: 'but you just did the one thing I wasn\'t expecting',
  lera_photo_ready: 'okay...',
  lera_photo_one: 'my choice. and it stays between us 😏',
  lera_photo_after: 'now I really want to see how you react',
  lera_warning_apology: 'apology accepted',
  lera_warning_a: 'but the photo topic is closed',
  lera_warning_b: 'push again and this conversation ends. I mean it',
  lera_gallery_photo: 'because you didn\'t ask. that changes a lot',
  lera_gallery_direct: 'yes. you finally asked me directly',
  lera_gallery_a: 'let\'s be specific',
  lera_gallery_b: 'what do you actually remember about me from the gallery?',
  lera_deleted_lie: 'and yes, I noticed that “I just tapped it” line earlier',
  lera_deleted_a: 'I just wrote something way too honest',
  lera_deleted_b: 'Message deleted',
  lera_deleted_c: 'okay. let\'s leave it there for now',
  lera_outfit_a: 'one detail is easier to show',
  lera_photo_two: 'this is the dress I wore at the gallery',
  lera_outfit_b: 'we never really met that night',
  lera_outfit_c: 'but I noticed you before you walked over to the red staircase',
  lera_reveal_start_calm: 'you opened with “we can just talk.” not a bad start',
  lera_reveal_start_ironic: 'remember my one honest answer? here it is',
  lera_reveal_start_confident: 'looks like your eye for detail won after all 😏',
  lera_reveal_start_flirty: 'apparently that terrible compliment survived the night',
  lera_reveal_start_risky: 'fine. you wanted no small talk, so here it is',
  lera_reveal_a: 'I asked Nadia to give you my contact',
  lera_reveal_b: 'I never texted you myself',
  lera_reveal_c: 'I wanted to see whether you would decide to write',
  lera_reveal_d: 'and whether you remembered me, not just a pretty dress',
  lera_final_lie: 'just don\'t hide behind “accidentally” again. I remember',
  lera_final_pressure: 'and my boundaries are still boundaries',
  lera_final_a: 'the test is over',
  lera_final_b: 'what do you want now—honestly?',
  lera_end_open_a: 'deal',
  lera_end_open_b: 'first message with no tests: tomorrow at ten ❤️',
  lera_end_date_a: 'coffee. tomorrow at 7:30',
  lera_end_date_b: 'and this time we\'ll actually meet 😏',
  lera_end_morning_a: 'sensible. good night... or good morning already 🙂',
  lera_end_distance_a: 'sometimes one honest night is enough. take care',
  lera_end_cold_a: 'I think we wanted different things from this conversation',
  lera_end_cold_b: 'you can continue without me. bye',
  lera_end_blocked_prelude_a: 'I already said no',
  lera_end_blocked_prelude_b: 'if you can\'t hear that, we really have nothing left to say',
  lera_end_blocked_a: 'Lera is no longer accepting messages',
  lera_end_secret_a: 'finally',
  lera_end_secret_b: 'I recognized you right away. I just wanted you to remember on your own 🤭',
  lera_end_secret_c: 'now we can start without the riddles',
};

const choiceText: Record<string, string> = {
  lera_start_calm: 'Hi. Nadia gave me your contact. Can\'t sleep?',
  lera_start_ironic: 'Do they hand out honest answers after midnight? Nadia gave me the address.',
  lera_start_confident: 'I think we were at the same gallery. I wanted to see if that was a coincidence.',
  lera_start_flirt: 'After that gallery, your “online” looks suspiciously good 😏',
  lera_start_risky: 'Skip the small talk. Why did Nadia give me your contact?',
  lera_calm_space: 'No catch. We can just talk.',
  lera_calm_question: '“Actually” makes it sound like you were waiting.',
  lera_ironic_match: 'Then I\'ll save my honest answer for later.',
  lera_ironic_push: 'Start with a question. We\'ll see how honest it is.',
  lera_confident_clear: 'Let\'s call it observant. I\'ll save the confidence for later.',
  lera_confident_bet: 'You can decide by morning. I\'m not rushing you.',
  lera_flirt_subtle: 'Then we\'ll keep it on the record.',
  lera_flirt_direct: 'Fair. I won\'t fill in the blanks for you.',
  lera_risky_honest: 'I did. Now we can start without the interrogation.',
  lera_risky_demand: 'Then prove this isn\'t another game.',
  lera_check_honest: 'After that gallery, you somehow stayed on my mind.',
  lera_check_tease: 'It\'s easier to text at night what you kept putting off all day.',
  lera_check_lie: 'Nadia sent the contact. I just tapped it.',
  lera_truth_respect: 'Deal. “No” does not need an explanation.',
  lera_truth_play: 'Deal. But we can still tease each other, right?',
  lera_truth_push: 'Rules are boring. We both know where this is going.',
  lera_respect_mood: 'What matters is you\'re home. No proof required.',
  lera_respect_words: 'No photo needed. Tell me what you\'re actually testing.',
  lera_respect_clue: 'Are you testing me—or thinking about that gallery?',
  lera_play_surprise: 'I can. Surprise me only if you genuinely want to.',
  lera_play_words: 'I can. Words are enough tonight.',
  lera_play_prove: 'The difference is whether you\'ll finally dare to send a photo.',
  lera_pressure_apologize: 'Fair. I pushed too far. I won\'t do it again.',
  lera_pressure_double: 'But you started this game.',
  lera_pressure_insult: 'Then explain why you had Nadia pass me your contact at all.',
  lera_no_photo_why: 'Don\'t rush. I\'m interested in you, not proof.',
  lera_no_photo_gallery: 'Are you testing whether I noticed you at the gallery?',
  lera_photo_expression: 'Beautiful. But I\'m more curious why you chose to send it right now.',
  lera_photo_warm: 'Now it\'s harder to pretend this conversation is completely innocent 😏',
  lera_photo_more: 'Beautiful. Got anything bolder?',
  lera_warning_listen: 'I hear you. I won\'t bring it up again.',
  lera_warning_argue: 'It\'s just a photo. You\'re making it complicated.',
  lera_warning_demand: 'Send it or we\'re done.',
  lera_gallery_truth: 'You were by the red-staircase painting and fixed the artist label.',
  lera_gallery_lie: 'Honestly? I remember a dark dress and the red staircase. Your face is blurry.',
  lera_deleted_wait: 'You don\'t have to put it back. I\'m not rushing you.',
  lera_deleted_ask: 'Was that a confession or another test?',
  lera_deleted_guess: 'You wanted to say you recognized me that night.',
  lera_deleted_crude: 'Probably another photo. Shame you deleted it.',
  lera_outfit_detail: 'Now I\'m sure. I remember the dress and you fixing the label.',
  lera_outfit_person: 'The dress helped. I care more about why you looked for me afterward.',
  lera_reveal_honest: 'I remembered you. Now I want to know you without the tests.',
  lera_reveal_careful: 'I don\'t remember everything. I won\'t invent what never happened.',
  lera_reveal_suspicious: 'So this entire conversation was one big test?',
  lera_final_open: 'Keep talking honestly. No masks, no more tests.',
  lera_final_date: 'Coffee tomorrow. This time we can actually meet.',
  lera_final_morning: 'Let\'s get some sleep and continue in the morning.',
  lera_final_distance: 'Let this night stay a beautiful story with no promises.',
  lera_final_accuse: 'These tests aren\'t for me. Let\'s stop here.',
  lera_final_block: 'Then send more photos first. I\'ll decide after.',
  lera_final_secret: 'You recognized me by the red staircase and waited for me to remember you.',
};

const messageAlt: Record<string, string> = {
  lera_photo_one: 'Lera, an adult woman age 24, takes a nighttime selfie at home in a closed, fully opaque dark-plum lingerie set.',
  lera_photo_two: 'Lera, an adult woman age 24, shows the closed dark-plum dress she wore to the gallery in a mirror.',
};

export const leraEnNodes: DialogueNode[] = leraRuNodes.map((node) => ({
  ...node,
  messages: node.messages.map((message) => {
    if (message.kind === 'delay') return { ...message };
    const text = messageText[message.id];
    if (!text) throw new Error(`[Lera EN] Missing message translation: ${message.id}`);
    return { ...message, text, alt: messageAlt[message.id] ?? message.alt };
  }),
  choices: node.choices?.map((choice) => {
    const text = choiceText[choice.id];
    if (!text) throw new Error(`[Lera EN] Missing choice translation: ${choice.id}`);
    return { ...choice, text };
  }),
}));
